### ISSUE TITLE
EnumPipe: Remove

### ISSUE THREAD

**Issue by flauc** [Jaspero/ng-helpers#7]
It isn't necessary anymore because angular now has a keyvalue pipe.

**Comment by makiJS** [comment]
https://angular.io/api/common/KeyValuePipe

Angular `keyvalue` pipe expects `key: number`

```
export class KeyValuePipeComponent {
  object: {[key: number]: string} = {2: 'foo', 1: 'bar'};
  map = new Map([[2, 'foo'], [1, 'bar']]);
}
```
